### PR TITLE
fix author misspelling

### PR DESCRIPTION
**Pull request by Crystallinqq**

### CODE REVIEW

**Comment by Crystallinqq** [comment]
hello?!?!?

**Comment by TheCodDev** [comment]
sounds like this man tryna put ANOTHER rat in w+3.

**Comment by YeahOMA** [comment]
Bro how do you rat people with comments

**Comment by omegabr99** [comment]
> sounds like this man tryna put ANOTHER rat in w+3.

r/minecraftclients brainlets be like

**Comment by 0x150** [comment]
> sounds like this man tryna put ANOTHER rat in w+3.

this one's safe

**Comment by Semisol** [comment]
brug moment

**Comment by Crystallinqq** [comment]
WHY WAS IT CLOSED.

**Comment by 0x150** [comment]
> WHY WAS IT CLOSED.

cum

**Comment by Semisol** [comment]
> WHY WAS IT CLOSED.

idek

**Comment by h0lloww** [comment]
madmeg is probably the worst paster ive ever seen

**Comment by Madmegsox1** [comment]
All of this is stuff I coded so please do your research before you make accusations otherwise it makes you look dumb, oh wait you are 😄

**Comment by h0lloww** [comment]
baby rage

**Comment by Crystallinqq** [comment]
> All of this is stuff I coded so please do your research before you make accusations otherwise it makes you look dumb, oh wait you are 😄

that is why u use access transformers, mixin accessors, and reflect api in the same project?

**Comment by Crystallinqq** [comment]
also u didnt code half the shit in this 😭

**Comment by h0lloww** [comment]
nigga u put @author with ur own name on someones curseforge mod 🐖🐷

**Comment by Officer32k** [comment]
phobos events....chinese client

**Pull request closed without merging**
